name: Daily Auto Commit

on:
  schedule:
    - cron: '7 0 * * *' # Runs every day at 00:07 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Make changes (optional)
        run: |
          echo "Automated commit at $(date)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily auto-commit: $(date)" || exit 0
          git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/George2Times/midnight-committer.git master
